services:
  krk-gala-26:
    build:
      context: .
      dockerfile: dockerfile
    container_name: krhacken-gala-game
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/krhacken_gala_26.db:/app/backend/krhacken_gala_26.db
      - ./backend/images:/app/backend/images
    networks:
      - caddy_net # Permet à ton conteneur Caddy global de le joindre

networks:
  caddy_net:
    external: true